-- PULSE PRE-RELEASE: realtime calling + push subscription foundation
-- Run in Supabase SQL Editor before testing calls.

create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  caller_id uuid not null references public.profiles(id) on delete cascade,
  callee_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'voice' check (kind in ('voice','video')),
  status text not null default 'ringing' check (status in ('ringing','accepted','declined','ended','missed')),
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  ended_at timestamptz
);

create index if not exists call_sessions_callee_idx on public.call_sessions(callee_id, created_at desc);
create index if not exists call_sessions_caller_idx on public.call_sessions(caller_id, created_at desc);

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.call_sessions(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('offer','answer','ice','hangup','busy')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists call_signals_recipient_idx on public.call_signals(recipient_id, created_at desc);
create index if not exists call_signals_call_idx on public.call_signals(call_id, created_at asc);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, endpoint)
);

alter table public.call_sessions enable row level security;
alter table public.call_signals enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists "call participants can read sessions" on public.call_sessions;
create policy "call participants can read sessions" on public.call_sessions for select
using (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists "users can create calls as caller" on public.call_sessions;
create policy "users can create calls as caller" on public.call_sessions for insert
with check (auth.uid() = caller_id);

drop policy if exists "call participants can update sessions" on public.call_sessions;
create policy "call participants can update sessions" on public.call_sessions for update
using (auth.uid() = caller_id or auth.uid() = callee_id)
with check (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists "call participants can read signals" on public.call_signals;
create policy "call participants can read signals" on public.call_signals for select
using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "users can send call signals" on public.call_signals;
create policy "users can send call signals" on public.call_signals for insert
with check (auth.uid() = sender_id);

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
create policy "users manage own push subscriptions" on public.push_subscriptions for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Realtime is used only for signaling events; actual media stays peer-to-peer.
alter table public.call_sessions replica identity full;
alter table public.call_signals replica identity full;

do $$ begin
  alter publication supabase_realtime add table public.call_sessions;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.call_signals;
exception when duplicate_object then null;
end $$;

comment on table public.call_signals is 'WebRTC signaling messages. Never store audio/video here.';
comment on table public.push_subscriptions is 'Browser/PWA push subscriptions for message and call notifications.';
